### PR TITLE
Dynamic ssl_config, email for iam user, readme update, template removal

### PR DESCRIPTION
**Pull request by timothechauvet**
Hey again, I was able to make it work with some changes to the code including

- Removing the [Template provider](https://registry.terraform.io/providers/hashicorp/template/2.2.0) which has been archived and didn't work on aarch64 macs
- Removing some typos on the readme and adding the [Preview Generator module](https://apps.nextcloud.com/apps/previewgenerator) installation for the next lines (I think you need to add `app:install previewgenerator`, I somehow got it wrong reviewing it)
- Adding the required email for the new IAM user (at least it didn't work without it on my config)
- Putting the policies on the tenancy scope instead of the compartment scope
- Put the `ssl_configuration` of the LB listener with a dynamic attribute (because we don't get any cert before running the config)

### CODE REVIEW

**Comment by bkk87** [comment]
Hey @timothechauvet ! I am very glad it is now working for you and you made good use out of it!

You definitely found some good stuff for improvement! Will need a few days to have a deeper look as I am currently busy with other things.

One thing I do not understand at first glance is the policy move from compartment to tenant. In general, I think it is useful to encapsulate all resources which belong to one deployment (nextcloud) into a compartment and not into the root account/tenant.

**Comment by bkk87** [comment]
Regarding the email attribute for the user I just doubled checked the terraform documentation and also  the Oracle web console. It is described as optional and I have not set it an email.

**Comment by timothechauvet** [comment]
Thanks for the consideration! For both email and tenancy compartment edits, I based everything off the errors I got from running the config on a brand new account, but I agree on the part that email should be optional according to the docs (even though Terraform asked me one for this)

Regarding the policies, I don't understand why it didn't work for me, but I'm agreeing on the fact that encapsulation makes the whole infrastructure better, but for some reason I received an error like "Compartment ocid isn't the same as the tenancy one" weirdly enough, reason why I pushed this edit

**Comment by bkk87** [comment]
thanks @timothechauvet for your contribution and fixes!

**Comment by bkk87** [comment]
I made the input var user_email nullable. In my case, I dont specify it. In your case, you can specify it so it is not making you any problems

**Pull request merged**
